name: Deploy HTML to Somee

on:
  push:
    branches:
      - main  # Hoặc 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. Lấy code từ GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Upload trực tiếp file HTML lên Somee
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: osstinh.somee.com
        username: thientinh
        password: Thientinh10
        
        # Thư mục chứa file index.html trên GitHub của bạn
        # Nếu file index.html nằm ngay ngoài cùng, để là ./
        # Nếu nằm trong thư mục con (ví dụ 'src'), đổi thành ./src/
        local-dir: ./
        
        # Đường dẫn trên server Somee (Thường là /www.ten_mien.somee.com/)
        server-dir: /www.osstinh.somee.com/
